### ISSUE TITLE
enableANSI: false does not hide all ANSI codes

### ISSUE THREAD

**Issue by NickJH** [SiaFoundation/hostd#282]
### Current Behavior

With `enableANSI: true` I can see the following in syslog (redirected to file):
```
Jan 25 19:32:50 hostd-test hostd[1645586]: #033[34mINFO#033[0m#011rhp3.LatestRevision#011RPC success#011{"sessionID": "da0a295d5c33be9a", "peerAddress": "20.2.220.34:47934", "rpcID": "562663676ac4277d", "elapsed": "209.570583ms"}
```
With `enableANSI: false` I see:
```
Jan 25 19:29:11 hostd-test hostd[1645414]: INFO#011rhp2.LoopSettings#011RPC success#011{"sessionID": "69bf4cdefe16a3c6", "peerAddr": "13.124.183.114:35586", "rpcID": "9998fe780c31c85b", "elapsed": "435.858µs"}
```
This still has the `#011` ANSI codes in it.

### Expected Behavior

The second line I mentioned should show:
```
Jan 25 19:29:11 hostd-test hostd[1645414]: INFO rhp2.LoopSettings#011RPC success {"sessionID": "69bf4cdefe16a3c6", "peerAddr": "13.124.183.114:35586", "rpcID": "9998fe780c31c85b", "elapsed": "435.858µs"}
```
So the `#011` should be replaced by a space or tab.

### Steps to Reproduce

In your hostd.yml have the following lines:
```
log:
  level: info # global log level
  stdout:
    enabled: true # enable logging to stdout
    level: info # log level for console logger
    format: human # log format (human, json)
    enableANSI: false # enable ANSI color codes (disabled on Windows)
```
To redirect syslog to file, use an rsyslog configlet:
```
if $programname == 'hostd' then /var/log/hostd/hostd.log
& stop
```

### Version

v1.0.2-beta.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04

### Anything else?

I did this test with the zen binaries on testnet.
