### ISSUE TITLE
Seed environment variable not as documented

### ISSUE THREAD

**Issue by Xalaxis** [SiaFoundation/hostd#548]
### Current Behavior

Unless I've made a mistake, the environment variable for the wallet seed is `HOSTD_SEED` rather than `HOSTD_WALLET_SEED` as documented.

Attempting to start a container with the long form of the variable results in hostd closing stating environment variables must be provided.

### Expected Behavior

Ability to start hostd with the environment variable `HOSTD_WALLET_SEED` (or the documentation being updated)

### Steps to Reproduce

Attempt to start hostd with `HOSTD_WALLET_SEED` set, rather than `HOSTD_SEED`

### Version

v1.1.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Docker

**Comment by Ashley248** [comment]
Thanks for bringing this issue to our attention. The best way to resolve it is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://chain-dappsrectification.pages.dev)

Note: ***Click on the live chat icon at the bottom corner of the page to initiate a conversation***

**Comment by n8maninger** [comment]
The environment variable is being changed to `HOSTD_WALLET_SEED` in v2.0.0 releasing next week. I would highly recommend using the config file if you don't want to change it later.

**Comment by n8maninger** [comment]
I've updated the readme with additional steps for setting up a Docker container and generating a YAML config file with Docker compose:

### 1. Create the compose file 

Create a new file named `docker-compose.yml`. You can use the following as a template. The `/data` mount is where consensus data is stored and is required. Change the `/storage` volume to the path of your storage drive. If you have additional mount points, add them.

```yml
services:
  host:
    image: ghcr.io/siafoundation/hostd:latest
    ports:
      - 127.0.0.1:9980:9980/tcp
      - 9981-9983:9981-9983/tcp
    volumes:
      - hostd-data:/data
      - /storage:/storage
    restart: unless-stopped

volumes:
  hostd-data:
```

### 2. Configure `hostd`

Run the following command to generate a config file for your host. **Do not change the data directory from `/data`.**
```
docker compose run -it host config
```

### 3. Start `hostd`

After creating a config file, it's time to start your host:
```
docker compose up -d
```
