### ISSUE TITLE
failed to add contract to store: transaction failed (attempt 1): failed to add contract: failed to insert contract

### ISSUE THREAD

**Issue by Druffib** [SiaFoundation/hostd#553]
### Current Behavior

My host is failing benchmarks and the SiaCentral troubleshooter after upgrading to v2.0.0-beta.1

HostD log shows

"failed to add contract to store: transaction failed (attempt 1): failed to add contract: failed to insert contract: disk I/O error: permission denied

SiaCentral shows RHP3 failure:
Reasons
error forming contract: host internal error

### Expected Behavior

Benchyd should compete a benchmark and return speed results / SiaCentral should show Host is working message

### Steps to Reproduce

1. Update hostd from 1.1.2 to v2.0.0-beta.1
2. Allow host to re-sync consensus ( in my case I copied consensus from renterd and then let hostd re-scan)
3. UI appears normal as if hostd is operating
4. Run benchyd scan or SiaCentral Troubleshooter
5. Observe utility failure report and check hostd log errors

### Version

v2.0.0-beta.1

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04

### Anything else?

I'm running via docker.  My compose file is largely unchanged from the prior release, other than updated the environment variable name for the wallet's seed.

**Comment by Druffib** [comment]
I've also set my data dir and my volume dirs to 777 perms , but, hostd log still shows permission errors.  In each volume I've mapped to store data files, I can seemingly create new volumes from the UI without generating a permission error.

**Comment by Druffib** [comment]
Compose file is:

```
services:
  hostd:
    container_name: hostd
    image: ghcr.io/siafoundation/hostd:2.0.0-beta.1
    user: "1000:1000"
    command: -http 0.0.0.0:39980 -syncer.address :39981 -rhp2 :39982 -rhp3 :39983
    environment:
      - HOSTD_WALLET_SEED=put in some seed phrase here please
      - HOSTD_API_PASSWORD=passwordsGoInThisSpot
    networks:
      - hostd
    ports:
      - 0.0.0.0:39980:39980/tcp
      - 39981-39984:39981-39984/tcp
    volumes:
      - /tank/sia/hostd/data:/data
      - /tank/sia/hostd/volumes:/volumes
      - /mnt/wwn-0x5000cca26cccd8d6/siadata:/volumes/vol8tb
      - /mnt/ata-WDC_WD80EMAZ-00WJTA0_1DGX9A2Z/siadata:/volumes/vol8Tbeta
    restart: unless-stopped
networks:
  hostd:
    driver_opts:
      com.docker.network.bridge.name: hostd
```


I've never used a hostd.yml file
