### ISSUE TITLE
Problem with RHP4 on all hosts

### ISSUE THREAD

**Issue by npelov** [SiaFoundation/hostd#720]
### Current Behavior

RHP 4 seems to not work.
It could be a problem with my configuration but I can't figure out what's wrong. Ports are open - tested by nmap from another machine on the internet
```
Issue testing RHP4 "quic" connection: failed to connect to quic: failed to connect to "siahost1.nicksoft.org:9984": timeout: no recent network activity
```

```
Issue testing RHP4 "quic" connection: failed to connect to quic: failed to connect to "siahost4.nicksoft.org:9989": timeout: no recent network activity
```

### Expected Behavior

RHP4 should be working

### Version

v2.3.0

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

docker on debian 12

### Anything else?

I'm using letsencrypt cert - a wildcard *.nicksoft.rg

docker command:
```
docker run -d \
  --pull=always \
  --name siahostd \
  --restart=unless-stopped \
  --env-file /appdata/siahostd/.env \
  -e PUID=3001 \
  -e PGID=3001 \
  -p 9980:9980 \
  -p 9981-9984:9981-9984 \
  -p 9984:9984/udp \
  -v /siadb/sia1:/data \
  -v /siastorage/sia1:/storagebig \
    ghcr.io/siafoundation/hostd:latest
```

I use my router to forward the ports to the local network.

my hostd.yml:
```
http:
  address: :9980
rhp2:
  address: :9982
rhp3:
  tcp: :9983
rhp4:
  listenAddresses:
    - protocol: tcp # tcp,tcp4 or tcp6
      address: :9984
    - protocol: quic # quic, quic4, quic6
      address: :9984
  quic:
    certPath: '/data/nicksoft.org/cert.pem' # Certificate chain file
    keyPath: '/data/nicksoft.org/privkey.pem' # Certificate private keyfile
log:
  level: info # global log level
  stdout:
    enabled: true # enable logging to stdout
    level: info # log level for console logger
    format: human # log format (human, json)
    enableANSI: true # enable ANSI color codes (disabled on Windows)
  file:
    enabled: true # enable logging to file
    level: warn # log level for file logger
    path: /data/hostd.log # the path of the log file
    format: json # log format (human, json)
```
